return return {
    ["The Depths"] = {
        ["Bobber"] = "Nautilis Shell",
        ["Name"] = "The Depths",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.380392, 0.145098, 0.145098,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://115528091268474",
        ["BadgeId"] = 2042505003241970,
    },
    ["Roslit"] = {
        ["Bobber"] = "Fake Pufferfish",
        ["Name"] = "Roslit Bay",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 1, 0.627451, 0.25098,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18542406497",
        ["BadgeId"] = 225841574756551,
    },
    ["LEGO"] = {
        ["Color"] = 1, 0.345098, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 450,
            ["Coins"] = 1200,
        },
        ["Banner"] = "rbxassetid://93788797229765",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Brickford's",
        ["EndTime"] = 1748001600000,
        ["StartTime"] = 1745323200000,
        ["Limited"] = true,
        ["BadgeId"] = 507614698244930,
    },
    ["Ancient Isle"] = {
        ["Bobber"] = "Amber",
        ["Name"] = "Ancient Isle",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.54902, 1, 0.760784,
        ["Rewards"] = {
            ["Xp"] = 10000,
            ["Coins"] = 50000,
        },
        ["Banner"] = "rbxassetid://79846684203518",
        ["BadgeId"] = 2054807830474099,
    },
    ["Sunstone"] = {
        ["Bobber"] = "Sun",
        ["Name"] = "Sunstone Island",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 1, 0.92549, 0.505882,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://108032910283682",
        ["BadgeId"] = 2903347774735091,
    },
    ["Animals1"] = {
        ["Color"] = 0.784314, 0.592157, 0.419608,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://98885094262535",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Animals",
        ["EndTime"] = 1745064000000,
        ["StartTime"] = 1743681600000,
        ["Limited"] = true,
        ["BadgeId"] = 4460712899366124,
    },
    ["Animals2"] = {
        ["Color"] = 0.784314, 0.592157, 0.419608,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://90754577751704",
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Animals - Sea 2",
        ["EndTime"] = 1745064000000,
        ["StartTime"] = 1743681600000,
        ["Limited"] = true,
        ["BadgeId"] = 1444909653191652,
    },
    ["Mushgrove"] = {
        ["Bobber"] = "Mushroom",
        ["Name"] = "Mushgrove Swamp",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.588235, 1, 0.4,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18952253458",
        ["BadgeId"] = 4343979385420841,
    },
    ["Winter's Edge"] = {
        ["Color"] = 1, 0.345098, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://102684908625295",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Winter's Edge",
        ["EndTime"] = 1735560000000,
        ["StartTime"] = 1735387200000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Keepers Altar"] = {
        ["Bobber"] = "Skeleton",
        ["Name"] = "Keepers Altar",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.247059, 0.278431, 0.72549,
        ["Rewards"] = {
            ["Xp"] = 1750,
            ["Coins"] = 1750,
        },
        ["Banner"] = "rbxassetid://131504032544120",
        ["BadgeId"] = 772547227400435,
    },
    ["Atlantean Storm"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Atlantean Storm",
        ["Color"] = 0.203922, 0.415686, 0.74902,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://102684908625295",
        ["BadgeId"] = 32642745294476,
    },
    ["Abyssal Zenith"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Abyssal Zenith",
        ["Color"] = 0.960784, 0.643137, 0.00392157,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://132690144896346",
        ["BadgeId"] = 440171660675783,
    },
    ["Blue Moon - Second Sea"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Blue Moon",
        ["Color"] = 0, 0.235294, 0.784314,
        ["Rewards"] = {
            ["Xp"] = 450,
            ["Coins"] = 450,
        },
        ["Banner"] = "rbxassetid://89920594828007",
        ["BadgeId"] = 1132127671855113,
    },
    ["Terrapin"] = {
        ["Bobber"] = "Mini Terrapin",
        ["Name"] = "Terrapin Island",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.341176, 1, 0.560784,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18791315983",
        ["BadgeId"] = 2994442057572213,
    },
    ["Blue Moon - First Sea"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Blue Moon",
        ["Color"] = 0, 0.235294, 0.784314,
        ["Rewards"] = {
            ["Xp"] = 450,
            ["Coins"] = 450,
        },
        ["Banner"] = "rbxassetid://89920594828007",
        ["BadgeId"] = 4358181133009953,
    },
    ["Octophant"] = {
        ["Color"] = 0.784314, 0.592157, 0.419608,
        ["Rewards"] = {
            ["Xp"] = 150,
            ["Coins"] = 1500,
        },
        ["Banner"] = "rbxassetid://106833572815626",
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Octophant",
        ["EndTime"] = 1745064000000,
        ["StartTime"] = 1743681600000,
        ["Limited"] = true,
        ["BadgeId"] = 2020919067872646,
    },
    ["Ancient Archives"] = {
        ["Bobber"] = "Ancient Book",
        ["Name"] = "Ancient Archives",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.219608, 0.329412, 0.160784,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://89908035795264",
        ["BadgeId"] = 1666493813690822,
    },
    ["Emberreach"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Emberreach",
        ["Color"] = 1, 0.368627, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://71592298810823",
        ["BadgeId"] = 2076076069924140,
    },
    ["Snowcap"] = {
        ["Bobber"] = "Frozen",
        ["Name"] = "Snowcap Island",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.647059, 1, 0.839216,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://101454347375454",
        ["BadgeId"] = 4101868524305507,
    },
    ["Glacial Grotto"] = {
        ["Bobber"] = "Frozen Rubber Ducky",
        ["Name"] = "Glacial Grotto",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.00392157, 0.631373, 0.72549,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://117435163084140",
        ["BadgeId"] = 1396071619017862,
    },
    ["Open Ocean"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Open Ocean",
        ["Color"] = 0.4, 0.509804, 1,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://80355788075086",
        ["BadgeId"] = 279267787604757,
    },
    ["Carrot Garden"] = {
        ["Bobber"] = "Rubber Ducky",
        ["Name"] = "Carrot Garden",
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Color"] = 1, 0.721569, 0.164706,
        ["Rewards"] = {
            ["Xp"] = 15000,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://79078668939907",
        ["BadgeId"] = 3871316346306270,
    },
    ["All"] = {
        ["Bobber"] = "Aurora",
        ["Name"] = "All",
        ["Worlds"] = {
            [1] = "Sea 1",
            [2] = "Sea 2",
        },
        ["Color"] = 1, 1, 1,
        ["Rewards"] = {
            ["Xp"] = 10000,
            ["Coins"] = 10000,
        },
        ["Banner"] = "rbxassetid://18310847126",
        ["BadgeId"] = 635398639427099,
    },
    ["Netter's Haven"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Netter's Haven",
        ["Color"] = 1, 0.819608, 0.701961,
        ["Rewards"] = {
            ["Xp"] = 450,
            ["Coins"] = 450,
        },
        ["Banner"] = "rbxassetid://86389473090589",
        ["BadgeId"] = 279267787604757,
    },
    ["Ashfall"] = {
        ["Color"] = 1, 0.294118, 0,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://71112448286941",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Ashfall",
        ["EndTime"] = 1740225600000,
        ["StartTime"] = 1739620800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Overgrowth Caves"] = {
        ["Bobber"] = "Frozen Rubber Ducky",
        ["Name"] = "Overgrowth Caves",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.00392157, 0.631373, 0.72549,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://105298630049350",
        ["BadgeId"] = 272078520028439,
    },
    ["Azure Lagoon"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Azure Lagoon",
        ["Color"] = 0.054902, 0.431373, 1,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://110878310521734",
        ["BadgeId"] = 2613933330373724,
    },
    ["The Cursed Shores"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "The Cursed Shores",
        ["Color"] = 0.32549, 0.109804, 0.32549,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://134898891181500",
        ["BadgeId"] = 410506324603873,
    },
    ["Cults Curse"] = {
        ["Color"] = 0.498039, 0.972549, 0.588235,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://121457195352472",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Cults Curse",
        ["EndTime"] = 1743249600000,
        ["StartTime"] = 1742644800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Frigid Cavern"] = {
        ["Bobber"] = "Frozen Rubber Ducky",
        ["Name"] = "Frigid Cavern",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.00392157, 0.631373, 0.72549,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://89444673055559",
        ["BadgeId"] = 843774301770016,
    },
    ["Lushgrove"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Lushgrove",
        ["Color"] = 0.207843, 0.301961, 0.0588235,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://95622266615149",
        ["BadgeId"] = 1997541657461197,
    },
    ["Roslit Volcano"] = {
        ["Bobber"] = "Lava",
        ["Name"] = "Roslit Volcano",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 1, 0.627451, 0.25098,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://108037427819021",
        ["BadgeId"] = 4479912445209985,
    },
    ["Veil of the Forsaken"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Veil of the Forsaken",
        ["Color"] = 0.960784, 0, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://107704595909248",
        ["BadgeId"] = 434000111228886,
    },
    ["Isle of New Beginnings"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Isle of New Beginnings",
        ["Color"] = 0.835294, 1, 0.00392157,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://94484023606927",
        ["BadgeId"] = 62688893003566,
    },
    ["Desolate Deep"] = {
        ["Bobber"] = "Infested",
        ["Name"] = "Desolate Deep",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.592157, 0.733333, 1,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://81573600788931",
        ["BadgeId"] = 3161443122784523,
    },
    ["Love"] = {
        ["Color"] = 1, 0.627451, 0.635294,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://115452311370526",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Love",
        ["EndTime"] = 1740225600000,
        ["StartTime"] = 1739016000000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Moosewood"] = {
        ["Bobber"] = "Rubber Ducky",
        ["Name"] = "Moosewood Island",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 1, 0.368627, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18310954523",
        ["BadgeId"] = 3871316346306270,
    },
    ["Challenger's Deep"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Challenger's Deep",
        ["Color"] = 0, 0.384314, 0.960784,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://104396195959351",
        ["BadgeId"] = 2580846320562382,
    },
    ["Calm Zone"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Calm Zone",
        ["Color"] = 0, 0.8, 0.960784,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://131041104295888",
        ["BadgeId"] = 699973517072777,
    },
    ["Vertigo"] = {
        ["Bobber"] = "Vertigo Rock",
        ["Name"] = "Vertigo",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.498039, 0.431373, 1,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18952306740",
        ["BadgeId"] = 3200076862852988,
    },
    ["Volcanic Vents"] = {
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Volcanic Vents",
        ["Color"] = 0.960784, 0.643137, 0.00392157,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://85665040701711",
        ["BadgeId"] = 2971899933109154,
    },
    ["FischFright"] = {
        ["Color"] = 0.333333, 0, 1,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://73235985228051",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "FischFright",
        ["EndTime"] = 1730635200000,
        ["StartTime"] = 1729252800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Crypt"] = {
        ["Color"] = 0.0705882, 0.282353, 0.0823529,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "http://www.roblox.com/asset/?id=129744094301723",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Crypt",
        ["EndTime"] = 1743422400000,
        ["StartTime"] = 1742644800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Waveborne"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Waveborne",
        ["Color"] = 1, 0.458824, 0.458824,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://91807982882576",
        ["BadgeId"] = 4035200905115276,
    },
    ["Forsaken Shores"] = {
        ["Bobber"] = "Pirate Wheel",
        ["Name"] = "Forsaken Shores",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.380392, 0.286275, 0.262745,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://124958348694122",
        ["BadgeId"] = 3591399443042848,
    },
    ["Ocean"] = {
        ["Bobber"] = "Anchor",
        ["Name"] = "Ocean",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.631373, 0.780392, 1,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://18310945663",
        ["BadgeId"] = 1045860405568363,
    },
    ["Archeological Site"] = {
        ["Color"] = 0.905882, 0.945098, 0.12549,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://71112448286941",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Archeological Site",
        ["EndTime"] = 1732968000000,
        ["StartTime"] = 1732363200000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Cryogenic Canal"] = {
        ["Bobber"] = "Frozen Rubber Ducky",
        ["Name"] = "Cryogenic Canal",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.00392157, 0.631373, 0.72549,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://117435163084140",
        ["BadgeId"] = 4189906956026791,
    },
    ["Fischmas"] = {
        ["Color"] = 1, 0.345098, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://137233586307916",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Fischmas",
        ["EndTime"] = 1735646400000,
        ["StartTime"] = 1734004800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Fischgiving"] = {
        ["Color"] = 0.862745, 0.368627, 0.0823529,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://133466398979921",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Fischgiving",
        ["EndTime"] = 1733400000000,
        ["StartTime"] = 1732190400000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Grand Reef"] = {
        ["Bobber"] = "Coral Reef",
        ["Name"] = "Grand Reef",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.231373, 0.72549, 0.454902,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://115456199795193",
        ["BadgeId"] = 968483808853747,
    },
    ["Brine Pool"] = {
        ["Bobber"] = "Brine",
        ["Name"] = "Brine Pool",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0.54902, 1, 0.54902,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://86510876700490",
        ["BadgeId"] = 1535329670769985,
    },
    ["Lucky Event"] = {
        ["Color"] = 1, 0.294118, 0,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://71112448286941",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Lucky Event",
        ["EndTime"] = 1711108800000,
        ["StartTime"] = 1710504000000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["Atlantis"] = {
        ["Bobber"] = "Coral Reef",
        ["Name"] = "Atlantis",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Color"] = 0, 0.784314, 1,
        ["Rewards"] = {
            ["Xp"] = 2500,
            ["Coins"] = 5000,
        },
        ["Banner"] = "rbxassetid://115456199795193",
        ["BadgeId"] = 2070428894950149,
    },
    ["Pine Shoal"] = {
        ["Worlds"] = {
            [1] = "Sea 2",
        },
        ["Name"] = "Pine Shoal",
        ["Color"] = 0.333333, 0.666667, 0.498039,
        ["Rewards"] = {
            ["Xp"] = 2000,
            ["Coins"] = 2000,
        },
        ["Banner"] = "rbxassetid://73795672350178",
        ["BadgeId"] = 3256592958077820,
    },
    ["Golden Tide"] = {
        ["Color"] = 1, 0.345098, 0.368627,
        ["Rewards"] = {
            ["Xp"] = 0,
            ["Coins"] = 0,
        },
        ["Banner"] = "rbxassetid://102684908625295",
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Golden Tide",
        ["EndTime"] = 1737806400000,
        ["StartTime"] = 1736596800000,
        ["Limited"] = true,
        ["Hide"] = true,
    },
    ["None"] = {
        ["Color"] = 1, 1, 1,
        ["Worlds"] = {
            [1] = "Sea 1",
        },
        ["Name"] = "Regionless",
        ["Banner"] = "rbxassetid://18310847126",
    },
}
