return {
    ["Resourceful Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 15000,
      ["Order"] = 83,
      ["Output"] = "Resourceful Rod",
      ["Items"] = {
        [1] = {
          [1] = "Amethyst",
          [2] = 3,
        },
        [2] = {
          [1] = "Driftwood",
          [2] = 2,
          [3] = "Lunar",
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Resourceful Rod",
      ["CraftOnce"] = true,
      ["Level"] = 50,
      ["Premium"] = false,
      ["Hint"] = "Reach level 50 to unlock this recipe",
    },
    ["Rod Of The Forgotten Fang"] = {
      ["Type"] = "Rod",
      ["Cost"] = 300000,
      ["Order"] = 90,
      ["Output"] = "Rod Of The Forgotten Fang",
      ["Items"] = {
        [1] = {
          [1] = "Meg's Fang",
          [2] = 2,
        },
        [2] = {
          [1] = "Meg's Spine",
          [2] = 2,
        },
        [3] = {
          [1] = "Lunar Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Rod Of The Forgotten Fang",
      ["CraftOnce"] = true,
      ["Level"] = 750,
      ["Premium"] = false,
      ["Hint"] = "Reach level 750 to unlock this recipe",
    },
    ["Precision Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 500,
      ["Order"] = 81,
      ["Output"] = "Precision Rod",
      ["Items"] = {
        [1] = {
          [1] = "Amethyst",
          [2] = 1,
        },
        [2] = {
          [1] = "Driftwood",
          [2] = 2,
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Precision Rod",
      ["CraftOnce"] = true,
      ["Level"] = 5,
      ["Premium"] = false,
      ["Hint"] = "Reach level 5 to unlock this recipe",
    },
    ["Celestial Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 100000,
      ["Order"] = 88,
      ["Output"] = "Celestial Rod",
      ["Items"] = {
        [1] = {
          [1] = "Moonstone",
          [2] = 2,
        },
        [2] = {
          [1] = "Moon Wood",
          [2] = 3,
        },
        [3] = {
          [1] = "Ancient Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Celestial Rod",
      ["CraftOnce"] = true,
      ["Level"] = 400,
      ["Premium"] = false,
      ["Hint"] = "Reach level 400 to unlock this recipe",
    },
    ["Wisdom Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 50000,
      ["Order"] = 82,
      ["Output"] = "Wisdom Rod",
      ["Items"] = {
        [1] = {
          [1] = "Ruby",
          [2] = 1,
        },
        [2] = {
          [1] = "Driftwood",
          [2] = 2,
          [3] = "Mythical",
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Wisdom Rod",
      ["CraftOnce"] = true,
      ["Level"] = 100,
      ["Premium"] = false,
      ["Hint"] = "Reach level 100 to unlock this recipe",
    },
    ["Voyager Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 30000,
      ["Order"] = 86,
      ["Output"] = "Voyager Rod",
      ["Items"] = {
        [1] = {
          [1] = "Opal",
          [2] = 3,
        },
        [2] = {
          [1] = "Void Wood",
          [2] = 3,
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Voyager Rod",
      ["CraftOnce"] = true,
      ["Level"] = 100,
      ["Premium"] = false,
      ["Hint"] = "Reach level 100 to unlock this recipe",
    },
    ["Seasons Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 35000,
      ["Order"] = 84,
      ["Output"] = "Seasons Rod",
      ["Items"] = {
        [1] = {
          [1] = "Opal",
          [2] = 2,
        },
        [2] = {
          [1] = "Driftwood",
          [2] = 3,
          [3] = "Frozen",
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Seasons Rod",
      ["CraftOnce"] = true,
      ["Level"] = 115,
      ["Premium"] = false,
      ["Hint"] = "Reach level 115 to unlock this recipe",
    },
    ["Rod Of The Eternal King"] = {
      ["Type"] = "Rod",
      ["Cost"] = 250000,
      ["Order"] = 89,
      ["Output"] = "Rod Of The Eternal King",
      ["Items"] = {
        [1] = {
          [1] = "Golden Sea Pearl",
          [2] = 2,
        },
        [2] = {
          [1] = "Inferno Wood",
          [2] = 3,
        },
        [3] = {
          [1] = "Lunar Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Rod Of The Eternal King",
      ["CraftOnce"] = true,
      ["Level"] = 650,
      ["Premium"] = false,
      ["Hint"] = "Reach level 650 to unlock this recipe",
    },
    ["Riptide Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 40000,
      ["Order"] = 85,
      ["Output"] = "Riptide Rod",
      ["Items"] = {
        [1] = {
          [1] = "Ruby",
          [2] = 3,
        },
        [2] = {
          [1] = "Driftwood",
          [2] = 3,
          [3] = "Atlantean",
        },
        [3] = {
          [1] = "Magic Thread",
          [2] = 1,
        },
      },
      ["Name"] = "Riptide Rod",
      ["CraftOnce"] = true,
      ["Level"] = 125,
      ["Premium"] = false,
      ["Hint"] = "Reach level 125 to unlock this recipe",
    },
    ["The Lost Rod"] = {
      ["Type"] = "Rod",
      ["Cost"] = 50000,
      ["Order"] = 87,
      ["Output"] = "The Lost Rod",
      ["Items"] = {
        [1] = {
          [1] = "Lapis Lazuli",
          [2] = 3,
        },
        [2] = {
          [1] = "Ancient Wood",
          [2] = 3,
        },
        [3] = {
          [1] = "Ancient Thread",
          [2] = 1,
        },
      },
      ["Name"] = "The Lost Rod",
      ["CraftOnce"] = true,
      ["Level"] = 150,
      ["Premium"] = false,
      ["Hint"] = "Reach level 150 to unlock this recipe",
    },
}
